seq_length: &seqlen 24 
model:
  base_learning_rate: 5.e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm_time.LatentDiffusion
  params:
    linear_start: 0.0005
    linear_end: 0.1
    num_timesteps_cond: 1
    log_every_t: 40
    timesteps: 1000
    loss_type: l1
    first_stage_key: "context"
    cond_stage_key: "context"
    seq_len: *seqlen
    channels: 7
    cond_stage_trainable: True
    concat_mode: False
    scale_by_std: False # True
    monitor: 'val/loss_simple_ema'
    conditioning_key: crossattn
    cond_drop_prob: 0.5

    unet_config:
      target: ldm.modules.diffusionmodules.ts_unet.UNetModel
      params:
        seq_len: *seqlen
        dims: 1
        in_channels: 7
        out_channels: 7
        model_channels: 64
        attention_resolutions: [ 1, 2, 4] 
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ] 
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        context_dim: 64
        repre_emb_channels: 32
        latent_unit: 1
        use_spatial_transformer: True
        num_classes: 2

    first_stage_config:  # no first stage model for ts data
      target: ldm.models.autoencoder.IdentityFirstStage  # VQModelInterface

    cond_stage_config:
      target: ldm.modules.encoders.modules.DomainUnifiedEncoder  # SplitTSEqEncoder # SplitTSEqEncoder, SingleTSEncoder
      params:
        dim: 32
        window: *seqlen
        latent_dim: 32  # 32 * 3
        num_channels: 7
        use_prototype: False
        # use_cfg: True

data:
  target: ldm.data.tsg_dataset.TSClassCondTrainDataModule
  params:
    data_path_dict:
      MIMIC_III_Readmission: icustay/train_tuple.pkl
    window: *seqlen
    val_portion: 0.1
    batch_size: 256
    num_workers: 8
    normalize: centered_pit
    drop_last: True
    reweight: False
    input_dim: 
lightning:
  callbacks:
    image_logger:
      target: utils.callback_utils.TSLogger
      params:
        # batch_frequency: 10
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: false

  trainer:
    benchmark: True
    max_steps: 20000